#!/usr/bin/perl -w
#
$line = 0;

open($files, 'find . -name "*.[hc|java]" |');
while (<$files>) {
        open($fp, $_);
        while (<$fp>) {
                $line++;
        }
}

print $line . "\n";
